name: ðŸ§® GitHub Metrics Daily

on:
  schedule:
    - cron: "0 6 * * *"  # midnight Central Time
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Aftabul-islam
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Chicago

          # Output & commit config
          filename: github-metrics.svg
          committer_branch: main
          committer_message: "chore: update metrics"

          # Plugins
          plugin_lines: yes
          plugin_languages: yes
          plugin_traffic: yes
          plugin_stars: yes
          plugin_isocalendar: yes
          plugin_habits: yes
          plugin_habits_facts: yes
